#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BACKPORT_FW_LOADER 1
#define CPTCFG_BACKPORT_OPTION_BT_SOCK_CREATE_NEEDS_KERN 1
#define CPTCFG_BACKPORT_AVERAGE 1
#define CPTCFG_BACKPORT_NEW_LEDS 1
#define CPTCFG_BACKPORT_LEDS_CLASS 1
#define CPTCFG_BACKPORT_LEDS_TRIGGERS 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_CFG80211_DEFAULT_PS 1
#define CPTCFG_CFG80211_DEBUGFS 1
#define CPTCFG_CFG80211_WEXT 1
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_RC_DEFAULT ""
#define CPTCFG_MAC80211_LEDS 1
#define CPTCFG_MAC80211_DEBUGFS 1
#define CPTCFG_MAC80211_MESSAGE_TRACING 1
#define CPTCFG_WLAN 1
#define CPTCFG_IWLWIFI_MODULE 1
#define CPTCFG_IWLDVM_MODULE 1
#define CPTCFG_IWLMVM_MODULE 1
#define CPTCFG_IWLWIFI_OPMODE_MODULAR 1
#define CPTCFG_IWLWIFI_DEBUG 1
#define CPTCFG_IWLWIFI_DEBUGFS 1
#define CPTCFG_IWLWIFI_DEVICE_TRACING 1
#define CPTCFG_RTL_CARDS_MODULE 1
#define CPTCFG_ETHERNET 1
#define CPTCFG_NET_VENDOR_ATHEROS 1
#define CPTCFG_NET_VENDOR_BROADCOM 1
#define CPTCFG_SSB_POSSIBLE 1
#define CPTCFG_BCMA_POSSIBLE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
